/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSwapRouteImport } from './routes/_app/swap'
import { Route as AppSendRouteImport } from './routes/_app/send'
import { Route as AppReceiveRouteImport } from './routes/_app/receive'
import { Route as AppQueriesRouteImport } from './routes/_app/queries'
import { Route as AppAccountRouteImport } from './routes/_app/account'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSwapRoute = AppSwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => AppRoute,
} as any)
const AppSendRoute = AppSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AppRoute,
} as any)
const AppReceiveRoute = AppReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => AppRoute,
} as any)
const AppQueriesRoute = AppQueriesRouteImport.update({
  id: '/queries',
  path: '/queries',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/account': typeof AppAccountRoute
  '/queries': typeof AppQueriesRoute
  '/receive': typeof AppReceiveRoute
  '/send': typeof AppSendRoute
  '/swap': typeof AppSwapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/account': typeof AppAccountRoute
  '/queries': typeof AppQueriesRoute
  '/receive': typeof AppReceiveRoute
  '/send': typeof AppSendRoute
  '/swap': typeof AppSwapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/queries': typeof AppQueriesRoute
  '/_app/receive': typeof AppReceiveRoute
  '/_app/send': typeof AppSendRoute
  '/_app/swap': typeof AppSwapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/account'
    | '/queries'
    | '/receive'
    | '/send'
    | '/swap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/account'
    | '/queries'
    | '/receive'
    | '/send'
    | '/swap'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/account'
    | '/_app/queries'
    | '/_app/receive'
    | '/_app/send'
    | '/_app/swap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/swap': {
      id: '/_app/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof AppSwapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/send': {
      id: '/_app/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof AppSendRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receive': {
      id: '/_app/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof AppReceiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/queries': {
      id: '/_app/queries'
      path: '/queries'
      fullPath: '/queries'
      preLoaderRoute: typeof AppQueriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppQueriesRoute: typeof AppQueriesRoute
  AppReceiveRoute: typeof AppReceiveRoute
  AppSendRoute: typeof AppSendRoute
  AppSwapRoute: typeof AppSwapRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppQueriesRoute: AppQueriesRoute,
  AppReceiveRoute: AppReceiveRoute,
  AppSendRoute: AppSendRoute,
  AppSwapRoute: AppSwapRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
